/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class BuscadorDeCarros extends javax.swing.JFrame {
    SistemaStopCar sistema;
    
    public BuscadorDeCarros(SistemaStopCar sistema) {
        this.sistema = sistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        categoriaBox = new javax.swing.JComboBox<>();
        placaInput1 = new javax.swing.JTextField();
        buscaPlaca = new javax.swing.JButton();
        placaLabel = new javax.swing.JLabel();
        buscaCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Pesquisa de carros");

        categoriaLabel.setText("Buscar por categoria:");

        categoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUV", "PICAPES", "CONVERSIVEIS" }));

        buscaPlaca.setText("Buscar");
        buscaPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscaPlacaMouseClicked(evt);
            }
        });
        buscaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaPlacaActionPerformed(evt);
            }
        });

        placaLabel.setText("Buscar por placa:");

        buscaCategoria.setText("Buscar");
        buscaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscaCategoriaMouseClicked(evt);
            }
        });
        buscaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoriaLabel)
                            .addComponent(placaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placaInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscaPlaca)
                            .addComponent(buscaCategoria))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaLabel)
                    .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placaLabel)
                    .addComponent(placaInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaPlaca))
                .addContainerGap(247, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaPlacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaPlacaMouseClicked
        Carro cl = sistema.buscaCarroPorPlaca(placaInput1.getText());

        if(cl == null){
            JOptionPane.showMessageDialog(null,"Tá nulo");
        }
        JOptionPane.showMessageDialog(null,cl);
    }//GEN-LAST:event_buscaPlacaMouseClicked

    private void buscaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaPlacaActionPerformed

    private void buscaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaCategoriaMouseClicked
        String s = (String) categoriaBox.getSelectedItem();
        System.out.println(s);

        if(s.equals("PICAPES")){
            ArrayList<Carro> carrosEncontrados = new ArrayList<>();
            carrosEncontrados = sistema.buscaCarroPorCategoria(CategoriaCarro.PICAPE);
            JOptionPane.showMessageDialog(null,carrosEncontrados);
        }
        if(s.equals("SUV")){
            ArrayList<Carro> carrosEncontrados = new ArrayList<>();
            carrosEncontrados = sistema.buscaCarroPorCategoria(CategoriaCarro.PICAPE);
            JOptionPane.showMessageDialog(null,carrosEncontrados);
        }
        if(s.equals("CONVERSIVEIS")){
            ArrayList<Carro> carrosEncontrados = new ArrayList<>();
            carrosEncontrados = sistema.buscaCarroPorCategoria(CategoriaCarro.PICAPE);
            JOptionPane.showMessageDialog(null,carrosEncontrados);
        }

    }//GEN-LAST:event_buscaCategoriaMouseClicked

    private void buscaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaCategoriaActionPerformed

    }//GEN-LAST:event_buscaCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorDeCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorDeCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorDeCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorDeCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscadorDeCarros buscadorCar = null;
                buscadorCar.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaCategoria;
    private javax.swing.JButton buscaPlaca;
    private javax.swing.JComboBox<String> categoriaBox;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField placaInput1;
    private javax.swing.JLabel placaLabel;
    // End of variables declaration//GEN-END:variables
}
