package telas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinic
 */
public class CarroFrame extends javax.swing.JFrame {
    SistemaStopCar sistema = new SistemaStopCar();
    public CarroFrame(SistemaStopCar sistema) {
        this.sistema = sistema;
        initComponents();
   
    }
    
    public CarroFrame (){
      
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        modeloLabel = new javax.swing.JLabel();
        modeloInput = new javax.swing.JTextField();
        placaLabel = new javax.swing.JLabel();
        placaInput = new javax.swing.JTextField();
        aluguelLabel = new javax.swing.JLabel();
        aluguelInput = new javax.swing.JTextField();
        picapeOption = new javax.swing.JRadioButton();
        suvOption = new javax.swing.JRadioButton();
        conversivelOption = new javax.swing.JRadioButton();
        cadastroCarros = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        modeloLabel.setText("Modelo:");

        placaLabel.setText("Placa:");

        aluguelLabel.setText("Aluguel km rodado:");

        buttonGroup1.add(picapeOption);
        picapeOption.setText("PICAPE");

        buttonGroup1.add(suvOption);
        suvOption.setText("SUV");

        buttonGroup1.add(conversivelOption);
        conversivelOption.setText("CONVERSIVEL");

        cadastroCarros.setText("Cadastrar");
        cadastroCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroCarrosActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cadastro de carros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aluguelLabel)
                                .addGap(18, 18, 18)
                                .addComponent(aluguelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modeloLabel)
                                .addGap(18, 18, 18)
                                .addComponent(modeloInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(placaLabel)
                                .addGap(29, 29, 29)
                                .addComponent(placaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(picapeOption)
                                .addGap(45, 45, 45)
                                .addComponent(suvOption)
                                .addGap(45, 45, 45)
                                .addComponent(conversivelOption)
                                .addGap(45, 45, 45)
                                .addComponent(cadastroCarros))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel7)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(placaLabel)
                        .addComponent(placaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(modeloInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aluguelLabel)
                    .addComponent(aluguelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picapeOption)
                    .addComponent(suvOption)
                    .addComponent(conversivelOption)
                    .addComponent(cadastroCarros))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroCarrosActionPerformed
        Carro novoCarro = new Carro(modeloInput.getText(),placaInput.getText(),Double.parseDouble(aluguelInput.getText()),CategoriaCarro.DESCONHECIDO);
        if(picapeOption.isSelected()){
            novoCarro.setCategoria(CategoriaCarro.PICAPE);
        }
         if(suvOption.isSelected()){
            novoCarro.setCategoria(CategoriaCarro.SUV);
        }
          if(conversivelOption.isSelected()){
            novoCarro.setCategoria(CategoriaCarro.CONVERSIVEL);
        }
        
        boolean cadastrou = sistema.cadastrarCarro(novoCarro);
        
        if(cadastrou){
            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso");
            
            //limpando campos
            modeloInput.setText("");
            placaInput.setText("");
            aluguelInput.setText("");
            
        }else{
            JOptionPane.showMessageDialog(null,"erro ao cadastrar");
        }
    }//GEN-LAST:event_cadastroCarrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarroFrame carro = null;
                carro.setVisible(false);
                carro.setSize(654,541);
                carro.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aluguelInput;
    private javax.swing.JLabel aluguelLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadastroCarros;
    private javax.swing.JRadioButton conversivelOption;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField modeloInput;
    private javax.swing.JLabel modeloLabel;
    private javax.swing.JRadioButton picapeOption;
    private javax.swing.JTextField placaInput;
    private javax.swing.JLabel placaLabel;
    private javax.swing.JRadioButton suvOption;
    // End of variables declaration//GEN-END:variables
}
