/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.Clock;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class stopCar extends javax.swing.JFrame {
    
    SistemaStopCar sistema = new SistemaStopCar();
    Date data = new Date();
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    AlugarFrame alugarFrame = new AlugarFrame(sistema);
    CarroFrame carro = new CarroFrame(sistema);
    DataCar save = new DataCar();
    public stopCar() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        AlugarItem = new javax.swing.JMenu();
        CadastrosItem = new javax.swing.JMenu();
        carrosMenu = new javax.swing.JMenuItem();
        clienteMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        buscaClientes = new javax.swing.JMenuItem();
        buscarCarros = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 69));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carrofacil-removebg.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/logo-removebg-preview.png"))); // NOI18N

        hora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 0, 102));
        hora.setText("jLabel3");

        AlugarItem.setText("Alugar");
        AlugarItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AlugarItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlugarItemMouseClicked(evt);
            }
        });
        AlugarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlugarItemActionPerformed(evt);
            }
        });
        jMenuBar1.add(AlugarItem);

        CadastrosItem.setText("Cadastrar");
        CadastrosItem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        carrosMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        carrosMenu.setText("Carros");
        carrosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carrosMenuMouseClicked(evt);
            }
        });
        carrosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrosMenuActionPerformed(evt);
            }
        });
        CadastrosItem.add(carrosMenu);

        clienteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        clienteMenu.setText("Clientes");
        clienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMenuActionPerformed(evt);
            }
        });
        CadastrosItem.add(clienteMenu);

        jMenuBar1.add(CadastrosItem);

        jMenu3.setText("Pesquisar");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        buscaClientes.setText("Pesquisar Clientes");
        buscaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaClientesActionPerformed(evt);
            }
        });
        jMenu3.add(buscaClientes);

        buscarCarros.setText("Pesquisar Carros");
        buscarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCarrosActionPerformed(evt);
            }
        });
        jMenu3.add(buscarCarros);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Sair");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 756, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMenuActionPerformed
       new ClienteFrame(sistema).setVisible(true);
       
    }//GEN-LAST:event_clienteMenuActionPerformed

    private void carrosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrosMenuActionPerformed
        new CarroFrame(sistema).setVisible(true);
    }//GEN-LAST:event_carrosMenuActionPerformed

    private void carrosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrosMenuMouseClicked

    }//GEN-LAST:event_carrosMenuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            hora.setText(formato.format(data));
            List<Cliente> clientes = save.recuperaUsuariosDeArquivo();
            List<Carro> carros = save.recuperaCarrosDeArquivo();
            this.sistema.recadastrandoClientes(clientes);
            this.sistema.recadastrandoCarros(carros);
            
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            alugarFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            save.gravaClienteEmArquivo(this.sistema.retornaTodosOsClientes());
            save.gravaCarroEmArquivo(this.sistema.retornaTodosOsCarros());
        } catch (IOException e) {
            // TODO Auto-generated catch block
            System.out.println(e.getMessage());
        }
         JOptionPane.showMessageDialog(null, "Até mais");
       
        
        
    }//GEN-LAST:event_formWindowClosing

    private void buscarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCarrosActionPerformed
        new BuscadorDeCarros(sistema).setVisible(true);
    }//GEN-LAST:event_buscarCarrosActionPerformed

    private void buscaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaClientesActionPerformed
        new BuscadorDeClientes(sistema).setVisible(true);
    }//GEN-LAST:event_buscaClientesActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        try {
            save.gravaClienteEmArquivo(this.sistema.retornaTodosOsClientes());
            save.gravaCarroEmArquivo(this.sistema.retornaTodosOsCarros());
        } catch (IOException e) {
            // TODO Auto-generated catch block
            System.out.println(e.getMessage());
        }
         JOptionPane.showMessageDialog(null, "Até mais");
               // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
           try {
            save.gravaClienteEmArquivo(this.sistema.retornaTodosOsClientes());
            save.gravaCarroEmArquivo(this.sistema.retornaTodosOsCarros());
        } catch (IOException e) {
            // TODO Auto-generated catch block
            System.out.println(e.getMessage());
        }
         JOptionPane.showMessageDialog(null, "Até mais");
         System.exit(0);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void AlugarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlugarItemActionPerformed
        
    }//GEN-LAST:event_AlugarItemActionPerformed

    private void AlugarItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlugarItemMouseClicked
        new AlugarFrame(sistema).setVisible(true);
    }//GEN-LAST:event_AlugarItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stopCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stopCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stopCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stopCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stopCar frame = new stopCar();
                frame.setVisible(true);
                frame.setExtendedState(MAXIMIZED_BOTH);
                frame.setResizable(false);
                frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AlugarItem;
    private javax.swing.JMenu CadastrosItem;
    private javax.swing.JMenuItem buscaClientes;
    private javax.swing.JMenuItem buscarCarros;
    private javax.swing.JMenuItem carrosMenu;
    private javax.swing.JMenuItem clienteMenu;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
